### ISSUE TITLE
Query.index returns the wrong element instead of failing if the index is too large

### ISSUE THREAD

**Issue by avh4** [eeue56/elm-html-test#45]
Example: https://ellie-app.com/jMLjSSNbBa1/0

```elm
import Html exposing (Html, text)
import Html.Attributes exposing (class)
import Test.Html.Query as Query
import Test.Html.Selector as Selector
import Test.Runner


html : Html msg
html =
    Html.div []
        [ Html.div [ class "a" ] [ text "0" ]
        , Html.div [ class "a" ] [ text "1" ]
        , Html.div [ class "a" ] [ text "2" ]
        ]


main : Html msg
main =
    html
        |> Query.fromHtml
        |> Query.findAll [ Selector.class "a" ]
        |> Query.index 3
        |> Query.has [ Selector.text "3" ]
        |> Test.Runner.getFailureReason
        |> Maybe.map .description
        |> Maybe.withDefault "PASSED"
        |> text
        |> List.singleton
        |> Html.pre []
```

**Expected**: `Query.findAll [ Selector.class "a" ] >> Query.index 3` should fail because there are only three results from the `findAll`
**Actual**: `Query.findAll [ Selector.class "a" ] >> Query.index 3` returns the first `div.a`

**Comment by stoeffel** [comment]
I think it's because of this: 

https://github.com/eeue56/elm-html-test/blob/10aee40ec259d0c17cabe1564375ae0c08891521/src/Test/Html/Query/Internal.elm#L244

I think we shouldn't modulo there:
https://github.com/eeue56/elm-html-test/blob/10aee40ec259d0c17cabe1564375ae0c08891521/src/Test/Html/Query/Internal.elm#L245

and just fail if the index is too low or too high.

**Comment by rtfeldman** [comment]
Yeah I agree - it seems like wraparound is causing surprising behavior here, and probably isn't worth it overall.
